# Generated by Django 4.0.1 on 2022-01-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('tag', models.CharField(max_length=10)),
                ('file', models.FileField(null=True, upload_to='')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
