# Generated by Django 4.0.1 on 2022-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0003_remove_video_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file2',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
